### ISSUE TITLE
Missing mutex directory after installation

### ISSUE THREAD

**Issue by shunwen** [svanzoest/apache2-cookbook#296]
Just noticed that after installation the `node['apache']['lock_dir']` is not created until the first time starting the apache2 service. It causes an error while installing passenger apache2 module, because that process tries to detect apache2 by running through the conf file and the missing lock folder would fail it.

I am wondering which is the better way to solve this issue -- create the folder in my own recipe, start apache2 after installation, or create the folder in this cookbook like other folders it creates in the `default` recipe? What do you think? 

Thanks!

**Comment by svanzoest** [comment]
Closing based on 03bd215, please create a new ticket and reference this if you see any related issues.
